apiVersion: v1
appVersion: 0.0.9
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: zeebe-knative-worker
version: 0.0.9
